[package]
name = "rust-rocket-site"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
rocket_contrib = "0.4.11"
rusqlite = "0.26.0"
rand = "0.8.5"
argon2 = "0.5.3"
regex = "1.10.3"
